package co.uk.amazon.pages;

import org.junit.Assert;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;

import java.util.List;
import java.util.Random;

public class SearchResultPage extends BasePage{

    public SearchResultPage(WebDriver driver)            // every page created
    {
        this.driver = driver;                            //must have
        PageFactory.initElements(driver, this);     //this constructor

    }

    @FindBy(css = ".a-section.a-spacing-small.a-spacing-top-small")
    private WebElement pageHeading;
    @FindBy(css = ".a-size-mini.a-spacing-none.a-color-base.s-line-clamp-2" )
    private List<WebElement> results; //list is used to make selenium aware there are many elements

    public void isSearchResultPageDisplayed(String item)
    {
        String url = driver.getCurrentUrl();
        Assert.assertTrue(url.contains(item));                          //to verify
    }

    //need to get the text of the pageHeading for validation
    public void doesPageTitleContain(String item)
    {
        String title = pageHeading.getText();
        Assert.assertTrue(title.contains(item)); //i want to extract title and ensure it contains item
        //get the text, assign it to the variable called title and then assert that it contains item
    }

//    public ProductDetailPage clickOnTheFirstResult()//telling selenium to click on the ist result
//    {
//        results.get(4).click();//0 represents the ist result
//        return  new ProductDetailPage(driver);
//    }
    public ProductDetailPage clickOnAnyResult()//telling selenium to click on the ist result
    {
        int noOfElement = results.size();//size will count the no of results and store the
                                         // value in the variable: noOfElement
        Random random = new Random();
        int ranNumber = random.nextInt( noOfElement-1);

        results.get(ranNumber).click();//any no generated by the variable, ranNumber is obtained by get
        return  new ProductDetailPage(driver);
    }
}